Login
shella12/RentAnItemBackend pull request #8
Opened 2023-05-08 11:52 UTC by ZuhRa-HashiMi

- [ ] Ruby on Rails App Creation and Initial Configuration
- [ ] Building the User Model and Session Controller for the Rails API Authentication App
- [ ] Implementing the Registration Controller and Final Authentication Features in Rails
- [ ] Configuring the Rails API Session Store to Work in All Environments

2023-05-08 16:24 UTC, shella12 requested changes
Hi @ZuhRa-HashiMi, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/l2Je9zHYveK012EVi/giphy.gif"/>

## Highlights

- Good commit history ✅ 
- Error while trying to run migrations ❌ 

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

2023-05-08 16:24 UTC, shella12 commented on config/credentials.yml.enc
- [ ] Please make sure that you don't update the `credential.yml.enc ` as it contains the master key which is unique to every app created using `rails new`. Please copy `credential.yml.enc ` from dev branch otherwise it's going to cause conflicts  for the rest of the team.

2023-05-08 16:24 UTC, shella12 requested changes
----

2023-05-09 05:32 UTC, ZuhRa-HashiMi commented on config/credentials.yml.enc
It's done. Thanks

2023-05-09 05:32 UTC, ZuhRa-HashiMi commented on README.md
It's done

2023-05-09 06:07 UTC, shella12 approved these changes
Hi @ZuhRa-HashiMi, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/KSIdkxVvqrbaR67SFN/giphy.gif"/>

## Highlights

- Fixed the crediential error ✔️ 
- README is professional 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-05-09 06:09 UTC, merged